apiVersion: v1
kind: ConfigMap
metadata:
  name: arrow-cache-config
  namespace: arrow-cache-imdb
data:
  METADATA_LOC: "s3://ricardo.hf.datasets/iceberg/hf_datasets.db/imdb_reviews/metadata/00003-132588d1-594d-4b12-99b1-d912667bba51.metadata.json"
  TABLE_NAME: "imdb_reviews"
  SCHEMA_NAME: "hf_datasets"
  RUST_LOG: "info"
  WORKER_RUNTIME: "KUBERNETES"
  LWS_GROUP_SIZE: "2"
  WORKER_SERVICE_NAME: "arrow-cache-worker-svc"
  NAMESPACE: "arrow-cache-imdb"
  # AWS Configuration
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "root-ricardo"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arrow-cache-worker-map
  namespace: arrow-cache-imdb
data:
  worker-mapping.json: |
    {
      "workers": [
        {
          "host": "arrow-cache-worker-0.arrow-cache-worker-svc.arrow-cache-imdb.svc.cluster.local",
          "port": 50051
        },
        {
          "host": "arrow-cache-worker-1.arrow-cache-worker-svc.arrow-cache-imdb.svc.cluster.local",
          "port": 50051
        }
      ]
    }
