apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use the base arrow-cache-imdb manifests and add IRSA service account
resources:
- ../../
- aws-service-account.yaml

# Patch deployments to remove AWS credentials and add service account
patchesStrategicMerge:
- head-deployment-patch.yaml
- worker-statefulset-patch.yaml
