apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-test
  namespace: arrow-cache-demo
spec:
  serviceAccountName: aws-service-account
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never
